name: fabpiks_web
description: Free Samples. Exciting brands

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  badges: ^3.1.2
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_razorpay_web: ^0.0.3
  flutter_share: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  flutter_windowmanager: ^0.2.0
  geolocator:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  im_stepper: ^1.0.1+1
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  latlong2: ^0.9.1
  lottie: ^3.1.2
  multi_select_flutter: ^4.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
#  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  responsive_sizer: ^3.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/animations/

  fonts:
    - family: "Montserrat"
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 900

    - family: "Poppins"
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900