name: fabpiks_web
description: Free Samples. Exciting brands

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  firebase_analytics: ^10.7.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5
  firebase_messaging: ^14.7.5
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_meta_sdk: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_razorpay_web: ^0.0.3
  flutter_share: ^2.0.0
  flutter_svg: ^2.0.9
  flutter_web_plugins:
    sdk: flutter
  flutter_windowmanager: ^0.2.0
  geolocator: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  im_stepper: ^1.0.1+1
  image_picker: ^1.0.4
  image_picker_web: ^3.1.1
  intl: ^0.19.0
  ionicons: ^0.2.2
  latlong2: ^0.9.0
  lottie: ^2.7.0
  multi_select_flutter: ^4.1.3
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  pinput: ^3.0.1
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  responsive_sizer: ^3.2.0
  url_launcher: ^6.2.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/animations/

  fonts:
    - family: "Montserrat"
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300

        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 900

    - family: "Poppins"
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
