// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDciMcgKDidDbzPtG6Zl-8ZEgWKr4aAX_4',
//     appId: '1:36553509936:web:4a551a3c4739964394b1f5',
//     messagingSenderId: '36553509936',
//     projectId: 'fabpiks-5e8c1',
//     authDomain: 'fabpiks-5e8c1.firebaseapp.com',
//     storageBucket: 'fabpiks-5e8c1.appspot.com',
//     measurementId: 'G-JLBGY2S2NF',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCTlWnKyAA1w_RhgO77d2dBJkLyTb3NxFk',
//     appId: '1:36553509936:android:6fc36153a47c014e94b1f5',
//     messagingSenderId: '36553509936',
//     projectId: 'fabpiks-5e8c1',
//     storageBucket: 'fabpiks-5e8c1.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB5EEqXQOSFE2fIgDGk4DJyB-hsLbBL7hQ',
//     appId: '1:36553509936:ios:bd561411a041663694b1f5',
//     messagingSenderId: '36553509936',
//     projectId: 'fabpiks-5e8c1',
//     storageBucket: 'fabpiks-5e8c1.appspot.com',
//     androidClientId: '36553509936-1romsc4n59v9m6h416smqlmc2c2usm68.apps.googleusercontent.com',
//     iosClientId: '36553509936-3fr9l44e9ucbnrj66c39qmecrt9567ht.apps.googleusercontent.com',
//     iosBundleId: 'com.fabpiks.fabpiks',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB5EEqXQOSFE2fIgDGk4DJyB-hsLbBL7hQ',
//     appId: '1:36553509936:ios:afb5384fce2b41c994b1f5',
//     messagingSenderId: '36553509936',
//     projectId: 'fabpiks-5e8c1',
//     storageBucket: 'fabpiks-5e8c1.appspot.com',
//     androidClientId: '36553509936-1romsc4n59v9m6h416smqlmc2c2usm68.apps.googleusercontent.com',
//     iosClientId: '36553509936-d6teen1k41ob49l6dctbscob9sb4uhal.apps.googleusercontent.com',
//     iosBundleId: 'com.fabpicks.fabpicks',
//   );
// }
